CREATE TABLE OBD2(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	GPS_TIME VARCHAR(100) NOT NULL,
  	DEVICE_TIME VARCHAR(12) NOT NULL,
  	LONGITUDE DECIMAL(8, 8) NOT NULL,
  	LATITUDE DECIMAL(8, 8) NOT NULL,
  	GPS_SPEED DECIMAL(8, 8) NOT NULL,
  	HORIZONTAL_DILUTION DECIMAL(3, 1) NOT NULL,
  	ALTITUDE DECIMAL(4, 2) NOT NULL,
  	BEARING DECIMAL(4, 2) NOT NULL,
  	GX DECIMAL(3, 2) NOT NULL,
  	GY DECIMAL(3, 2) NOT NULL,
  	GZ DECIMAL(3, 2) NOT NULL,
  	GCALIBRATED VARCHAR(20) NOT NULL,
  	ENGINE_COOLANT_TEMPERATURE DECIMAL(3, 1) NOT NULL,
  	ENGINE_RPM DECIMAL(5, 2) NOT NULL,
  	INTAKE_AIRTEMPERATURE DECIMAL(3, 1) NOT NULL,
  	ENGINE_LOAD DECIMAL(8, 8) NOT NULL,
  	MASS_AIR_FLOW DECIMAL(8, 8) NOT NULL,
  	THROTTLE_POSSITION DECIMAL (8, 8) NOT NULL,
  	PRIMARY KEY(ID)
);

